AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for FastAPI app running on AWS Lambda + API Gateway (HTTP)

Globals:
  Function:
    Timeout: 30
    Runtime: python3.10
    MemorySize: 512
    Architectures:
      - x86_64
    Environment:
      Variables:
        PYTHONPATH: /var/task

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fastapi-fitness-app
      CodeUri: .
      Handler: app.lambda_handler    # from app.py
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiGatewayEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for FastAPI function"
    Value:
      Fn::Sub: "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
