AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_handler.handler
      Runtime: python3.10
      CodeUri: ./app
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        RootApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        ProxyApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value:
      Fn::Sub: "https://${FastAPIFunction.HttpApiId}.execute-api.${AWS::Region}.amazonaws.com/"
